# Do NOT edit this file!
# It was generated by IdlC from CardReader.idl.

use strict;

package Raritan::RPC::smartcard::CardReader::CardInsertedEvent;

use constant typeId => "smartcard.CardReader.CardInsertedEvent:1.0.0";
use Raritan::RPC::smartcard::CardReader::CardEvent;

sub encode {
    my ($in) = @_;
    my $encoded = Raritan::RPC::smartcard::CardReader::CardEvent::encode($in);
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = Raritan::RPC::smartcard::CardReader::CardEvent::decode($agent, $in);
    return $decoded;
}

Raritan::RPC::Registry::registerCodecClass('smartcard.CardReader.CardInsertedEvent', 1, 0, 0, 'Raritan::RPC::smartcard::CardReader::CardInsertedEvent');
1;
