# Do NOT edit this file!
# It was generated by IdlC from CardReader.idl.

use strict;

package Raritan::RPC::smartcard::CardReader::CardInformation;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'type'} = "$in->{'type'}";
    $encoded->{'uid'} = "$in->{'uid'}";
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'type'} = $in->{'type'};
    $decoded->{'uid'} = $in->{'uid'};
    return $decoded;
}

1;
