# Do NOT edit this file!
# It was generated by IdlC from CardReader.idl.

use strict;

package Raritan::RPC::smartcard::CardReader::MetaData;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'manufacturer'} = "$in->{'manufacturer'}";
    $encoded->{'product'} = "$in->{'product'}";
    $encoded->{'serialNumber'} = "$in->{'serialNumber'}";
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'manufacturer'} = $in->{'manufacturer'};
    $decoded->{'product'} = $in->{'product'};
    $decoded->{'serialNumber'} = $in->{'serialNumber'};
    return $decoded;
}

1;
