# Do NOT edit this file!
# It was generated by IdlC from ResMon.idl.

use strict;

package Raritan::RPC::res_mon::Entry;


sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'type'} = $in->{'type'};
    $encoded->{'name'} = "$in->{'name'}";
    $encoded->{'value'} = 1 * $in->{'value'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'type'} = $in->{'type'};
    $decoded->{'name'} = $in->{'name'};
    $decoded->{'value'} = $in->{'value'};
    return $decoded;
}

1;
