# Do NOT edit this file!
# It was generated by IdlC from AccumulatingNumericSensor.idl.

use strict;

package Raritan::RPC::sensors::AccumulatingNumericSensor::Events;

use constant EVT_KEY_VALUE_RESET => 0;

1;
