# Do NOT edit this file!
# It was generated by IdlC from LuaService.idl.

use strict;

package Raritan::RPC::luaservice::ScriptState::ExecState;

use constant STAT_NEW => 0;
use constant STAT_RUNNING => 1;
use constant STAT_TERMINATED => 2;
use constant STAT_RESTARTING => 3;

1;
