# Do NOT edit this file!
# It was generated by IdlC from LuaService.idl.

use strict;

package Raritan::RPC::luaservice::ScriptState::ExitType;

use constant EXIT_CODE => 0;
use constant SIGNAL => 1;

1;
