# Do NOT edit this file!
# It was generated by IdlC from Lhx.idl.

use strict;

package Raritan::RPC::lhxmodel::Lhx_1_0_1::Events;

use constant EVT_KEY_OPSTATE_CHANGED => 0;
use constant EVT_KEY_SETTINGS_CHANGED => 1;

1;
