# Do NOT edit this file!
# It was generated by IdlC from Pdu.idl.

use strict;

package Raritan::RPC::pdumodel::Pdu_2_2_2::StartupState;

use constant SS_ON => 0;
use constant SS_OFF => 1;
use constant SS_LASTKNOWN => 2;

1;
