# Do NOT edit this file!
# It was generated by IdlC from InternalBeeper.idl.

use strict;

package Raritan::RPC::hmi::InternalBeeper::MuteChangedEvent;

use constant typeId => "hmi.InternalBeeper.MuteChangedEvent:1.0.0";
use Raritan::RPC::event::UserEvent;

sub encode {
    my ($in) = @_;
    my $encoded = Raritan::RPC::event::UserEvent::encode($in);
    $encoded->{'muted'} = ($in->{'muted'}) ? JSON::true : JSON::false;
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = Raritan::RPC::event::UserEvent::decode($agent, $in);
    $decoded->{'muted'} = ($in->{'muted'}) ? 1 : 0;
    return $decoded;
}

Raritan::RPC::Registry::registerCodecClass('hmi.InternalBeeper.MuteChangedEvent', 1, 0, 0, 'Raritan::RPC::hmi::InternalBeeper::MuteChangedEvent');
1;
