# Do NOT edit this file!
# It was generated by IdlC from BulkRequest.idl.

use strict;

package Raritan::RPC::bulkrpc::Request;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'rid'} = "$in->{'rid'}";
    $encoded->{'json'} = "$in->{'json'}";
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'rid'} = $in->{'rid'};
    $decoded->{'json'} = $in->{'json'};
    return $decoded;
}

1;
