# Do NOT edit this file!
# It was generated by IdlC from BulkRequest.idl.

use strict;

package Raritan::RPC::bulkrpc::Response;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'json'} = "$in->{'json'}";
    $encoded->{'statcode'} = 1 * $in->{'statcode'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'json'} = $in->{'json'};
    $decoded->{'statcode'} = $in->{'statcode'};
    return $decoded;
}

1;
