# Do NOT edit this file!
# It was generated by IdlC from AssetStrips.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetStrips::Info;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'numberOfAssetStrips'} = 1 * $in->{'numberOfAssetStrips'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'numberOfAssetStrips'} = $in->{'numberOfAssetStrips'};
    return $decoded;
}

1;
