# Do NOT edit this file!
# It was generated by IdlC from PowerMeter.idl.

use strict;

package Raritan::RPC::pdumodel::PowerMeter::SettingsChangedEvent;

use constant typeId => "pdumodel.PowerMeter.SettingsChangedEvent:1.0.0";
use Raritan::RPC::pdumodel::PowerMeter::Settings;
use Raritan::RPC::event::UserEvent;
use Raritan::RPC::pdumodel::PowerMeter::Settings;

sub encode {
    my ($in) = @_;
    my $encoded = Raritan::RPC::event::UserEvent::encode($in);
    $encoded->{'oldSettings'} = Raritan::RPC::pdumodel::PowerMeter::Settings::encode($in->{'oldSettings'});
    $encoded->{'newSettings'} = Raritan::RPC::pdumodel::PowerMeter::Settings::encode($in->{'newSettings'});
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = Raritan::RPC::event::UserEvent::decode($agent, $in);
    $decoded->{'oldSettings'} = Raritan::RPC::pdumodel::PowerMeter::Settings::decode($agent, $in->{'oldSettings'});
    $decoded->{'newSettings'} = Raritan::RPC::pdumodel::PowerMeter::Settings::decode($agent, $in->{'newSettings'});
    return $decoded;
}

Raritan::RPC::Registry::registerCodecClass('pdumodel.PowerMeter.SettingsChangedEvent', 1, 0, 0, 'Raritan::RPC::pdumodel::PowerMeter::SettingsChangedEvent');
1;
