# Do NOT edit this file!
# It was generated by IdlC from PowerMeter.idl.

use strict;

package Raritan::RPC::pdumodel::PowerMeter::Type;

use constant ONE_PHASE => 0;
use constant SPLIT_PHASE => 1;
use constant THREE_PHASE => 2;

1;
