# Do NOT edit this file!
# It was generated by IdlC from PeripheralDeviceManager.idl.

use strict;

package Raritan::RPC::peripheral::DeviceManager_1_0_3::ZCoordMode;

use constant RACKUNITS => 0;
use constant FREEFORM => 1;

1;
