# Do NOT edit this file!
# It was generated by IdlC from ExternalSensorSlot.idl.

use strict;

package Raritan::RPC::sensors::ExternalSensorSlot_2_0_0::Events;

use constant EVT_KEY_INFO_CHANGED => 0;

1;
