# Do NOT edit this file!
# It was generated by IdlC from EventEngine.idl.

use strict;

package Raritan::RPC::event::Engine::Condition::Op;

use constant AND => 0;
use constant OR => 1;
use constant XOR => 2;

1;
