# Do NOT edit this file!
# It was generated by IdlC from ExternalBeeper.idl.

use strict;

package Raritan::RPC::hmi::ExternalBeeper_1_0_1::State;

use constant OFF => 0;
use constant ON => 1;
use constant ALARMING => 2;

1;
