# Do NOT edit this file!
# It was generated by IdlC from Bcm.idl.

use strict;

package Raritan::RPC::pdumodel::Bcm::LineConfig;

use constant UNCONNECTED => 0;
use constant L1_N => 1;
use constant L2_N => 2;
use constant L3_N => 3;

1;
