# Do NOT edit this file!
# It was generated by IdlC from NumericSensor.idl.

use strict;

package Raritan::RPC::sensors::NumericSensor_3_0_1::Events;

use constant EVT_KEY_READING => 0;
use constant EVT_KEY_STATE => 1;
use constant EVT_KEY_METADATA => 2;
use constant EVT_KEY_THRESHOLDS => 3;

1;
