# Do NOT edit this file!
# It was generated by IdlC from Outlet.idl.

use strict;

package Raritan::RPC::pdumodel::Outlet_2_0_0::StartupState;

use constant SS_ON => 0;
use constant SS_OFF => 1;
use constant SS_LASTKNOWN => 2;
use constant SS_PDUDEF => 3;

1;
