# Do NOT edit this file!
# It was generated by IdlC from OverCurrentProtector.idl.

use strict;

package Raritan::RPC::pdumodel::OverCurrentProtector::Events;

use constant EVT_KEY_SETTINGS_CHANGED => 0;

1;
