# Do NOT edit this file!
# It was generated by IdlC from BulkRequest.idl.

use strict;

package Raritan::RPC::bulkrpc::BulkRequest_1_0_2::Request;

use Raritan::RPC::bulkrpc::JsonObject;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'rid'} = "$in->{'rid'}";
    $encoded->{'json'} = Raritan::RPC::bulkrpc::JsonObject::encode($in->{'json'});
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'rid'} = $in->{'rid'};
    $decoded->{'json'} = Raritan::RPC::bulkrpc::JsonObject::decode($agent, $in->{'json'});
    return $decoded;
}

1;
