# Do NOT edit this file!
# It was generated by IdlC from SerialPort.idl.

use strict;

package Raritan::RPC::serial::SerialPort_3_0_0::DetectionType;

use constant AUTOMATIC => 0;
use constant FORCE_CONSOLE => 1;
use constant FORCE_ANALOGMODEM => 2;
use constant FORCE_GSMMODEM => 3;

1;
