# Do NOT edit this file!
# It was generated by IdlC from SerialPort.idl.

use strict;

package Raritan::RPC::serial::SerialPort_3_0_0::Settings;


sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'consoleBaudRate'} = $in->{'consoleBaudRate'};
    $encoded->{'modemBaudRate'} = $in->{'modemBaudRate'};
    $encoded->{'detectType'} = $in->{'detectType'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'consoleBaudRate'} = $in->{'consoleBaudRate'};
    $decoded->{'modemBaudRate'} = $in->{'modemBaudRate'};
    $decoded->{'detectType'} = $in->{'detectType'};
    return $decoded;
}

1;
