# Do NOT edit this file!
# It was generated by IdlC from Controller.idl.

use strict;

package Raritan::RPC::pdumodel::Controller::Type;

use constant OUTLET_CTRL => 0;
use constant INLET_CTRL => 1;

1;
