# Do NOT edit this file!
# It was generated by IdlC from TransferSwitch.idl.

use strict;

package Raritan::RPC::pdumodel::TransferSwitch_3_0_0::Events;

use constant EVT_KEY_SETTINGS_CHANGED => 0;

1;
