# Do NOT edit this file!
# It was generated by IdlC from ServerMonitor.idl.

use strict;

package Raritan::RPC::servermon::ServerMonitor::ServerReachability;

use constant WAITING => 0;
use constant REACHABLE => 1;
use constant UNREACHABLE => 2;
use constant ERROR => 3;

1;
