# Do NOT edit this file!
# It was generated by IdlC from TestDisplay.idl.

use strict;

package Raritan::RPC::test::Display_1_0_1::TestStatus;

use constant TEST_IDLE => 0;
use constant TEST_BUSY => 1;
use constant TEST_PASSED => 2;
use constant TEST_FAILED => 3;

1;
