# Do NOT edit this file!
# It was generated by IdlC from LhxSensor.idl.

use strict;

package Raritan::RPC::lhxmodel::Sensor::Events;

use constant EVT_KEY_THRESHOLDS => 0;
use constant EVT_KEY_STATE => 1;
use constant EVT_KEY_NUM_READING => 2;

1;
