# Do NOT edit this file!
# It was generated by IdlC from AssetStrip.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetStrip_2_0_1::StripType;

use constant SIMPLE => 0;
use constant COMPOSITE => 1;

1;
