# Do NOT edit this file!
# It was generated by IdlC from PowerMeterController.idl.

use strict;

package Raritan::RPC::pdumodel::PowerMeterController::ScanResult;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'present'} = ($in->{'present'}) ? JSON::true : JSON::false;
    $encoded->{'meterCount'} = 1 * $in->{'meterCount'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'present'} = ($in->{'present'}) ? 1 : 0;
    $decoded->{'meterCount'} = $in->{'meterCount'};
    return $decoded;
}

1;
