# Do NOT edit this file!
# It was generated by IdlC from InternalBeeper.idl.

use strict;

package Raritan::RPC::hmi::InternalBeeper_2_0_0::State;

use constant OFF => 0;
use constant ON_NOTIFICATION => 1;
use constant ON_ACTIVATION => 2;

1;
