# Do NOT edit this file!
# It was generated by IdlC from Outlet.idl.

use strict;

package Raritan::RPC::pdumodel::Outlet_1_4_5::Events;

use constant EVT_KEY_STATE_CHANGE => 0;
use constant EVT_KEY_SETTINGS_CHANGE => 1;

1;
