# Do NOT edit this file!
# It was generated by IdlC from EventEngine.idl.

use strict;

package Raritan::RPC::event::Engine::EventDesc::Type;

use constant NODE => 0;
use constant DYN_NODE => 1;
use constant LEAF => 2;

1;
