# Do NOT edit this file!
# It was generated by IdlC from LhxDevel.idl.

use strict;

package Raritan::RPC::lhxmodel::LhxDevel_1_1_1;

use parent qw(Raritan::RPC::lhxmodel::Lhx_3_2_2);

use constant typeId => "lhxmodel.LhxDevel:1.1.1";

sub new {
    my ($class, $agent, $rid, $typeId) = @_;
    $typeId = $typeId || Raritan::RPC::lhxmodel::LhxDevel_1_1_1::typeId;
    return $class->SUPER::new($agent, $rid, $typeId);
}

use Raritan::RPC::lhxmodel::LhxDevel_1_1_1::ParameterData;

sub dumpParameter($) {
    my ($self) = @_;
    my $agent = $self->{'agent'};
    my $args = {};
    my $rsp = $agent->json_rpc($self->{'rid'}, 'dumpParameter', $args);
    my $_ret_;
    $_ret_ = [];
    for (my $i0 = 0; $i0 <= $#{$rsp->{'_ret_'}}; $i0++) {
        $_ret_->[$i0] = Raritan::RPC::lhxmodel::LhxDevel_1_1_1::ParameterData::decode($agent, $rsp->{'_ret_'}->[$i0]);
    }
    return $_ret_;
}

Raritan::RPC::Registry::registerProxyClass('lhxmodel.LhxDevel', 1, 1, 1, 'Raritan::RPC::lhxmodel::LhxDevel_1_1_1');
1;
