# Do NOT edit this file!
# It was generated by IdlC from PeripheralDevicePackage.idl.

use strict;

package Raritan::RPC::peripheral::PackageInfo::FirmwareInfo::Version;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'majorNumber'} = 1 * $in->{'majorNumber'};
    $encoded->{'minorNumber'} = 1 * $in->{'minorNumber'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'majorNumber'} = $in->{'majorNumber'};
    $decoded->{'minorNumber'} = $in->{'minorNumber'};
    return $decoded;
}

1;
