# Do NOT edit this file!
# It was generated by IdlC from testrpc.idl.

use strict;

package Raritan::RPC::test::Ethernet::Speed;

use constant SPD_10 => 0;
use constant SPD_100 => 1;
use constant SPD_1000 => 2;

1;
