# Do NOT edit this file!
# It was generated by IdlC from SnmpV3.idl.

use strict;

package Raritan::RPC::um::SnmpV3::SecurityLevel;

use constant NO_AUTH_NO_PRIV => 0;
use constant AUTH_NO_PRIV => 1;
use constant AUTH_PRIV => 2;

1;
