# Do NOT edit this file!
# It was generated by IdlC from Panel.idl.

use strict;

package Raritan::RPC::pdumodel::Panel_1_0_1::LabelingScheme;

use constant SEQUENTIAL => 0;
use constant ODD_EVEN => 1;

1;
