# Do NOT edit this file!
# It was generated by IdlC from SessionManager.idl.

use strict;

package Raritan::RPC::session::SessionManager_2_0_0::CloseReason;

use constant CLOSE_REASON_LOGOUT => 0;
use constant CLOSE_REASON_TIMEOUT => 1;
use constant CLOSE_REASON_BROWSER_CLOSED => 2;
use constant CLOSE_REASON_FORCED_DISCONNECT => 3;

1;
