# Do NOT edit this file!
# It was generated by IdlC from Port.idl.

use strict;

package Raritan::RPC::portsmodel::Port_2_0_0::DetectionType;

use constant AUTO => 0;
use constant PINNED => 1;
use constant DISABLED => 2;

1;
