# Do NOT edit this file!
# It was generated by IdlC from Port.idl.

use strict;

package Raritan::RPC::portsmodel::Port_2_0_0::Events;

use constant EVT_KEY_PROPS_CHANGED => 0;
use constant EVT_KEY_DEVICE_CHANGED => 1;

1;
