# Do NOT edit this file!
# It was generated by IdlC from Sensor.idl.

use strict;

package Raritan::RPC::sensors::Sensor::ReadingType;

use constant NUMERIC => 0;
use constant DISCRETE_ON_OFF => 1;
use constant DISCRETE_MULTI => 2;

1;
