# Do NOT edit this file!
# It was generated by IdlC from StorageManager.idl.

use strict;

package Raritan::RPC::webcam::StorageManager_1_0_1::Activity;


sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'webcam'} = Raritan::RPC::ObjectCodec::encode($in->{'webcam'});
    $encoded->{'interval'} = 1 * $in->{'interval'};
    $encoded->{'count'} = 1 * $in->{'count'};
    $encoded->{'done'} = 1 * $in->{'done'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'webcam'} = Raritan::RPC::ObjectCodec::decode($agent, $in->{'webcam'}, 'webcam.Webcam');
    $decoded->{'interval'} = $in->{'interval'};
    $decoded->{'count'} = $in->{'count'};
    $decoded->{'done'} = $in->{'done'};
    return $decoded;
}

1;
