# Do NOT edit this file!
# It was generated by IdlC from StorageManager.idl.

use strict;

package Raritan::RPC::webcam::StorageManager_1_0_1::StorageStatus;

use constant INITIALIZING => 0;
use constant READY => 1;

1;
