# Do NOT edit this file!
# It was generated by IdlC from StorageManager.idl.

use strict;

package Raritan::RPC::webcam::StorageManager_1_0_1::StorageType;

use constant LOCAL => 0;
use constant FTP => 1;
use constant CIFS => 2;
use constant NFS => 3;

1;
