# Do NOT edit this file!
# It was generated by IdlC from StorageManager.idl.

use strict;

package Raritan::RPC::webcam::StorageManager::Direction;

use constant ASCENDING => 0;
use constant DESCENDING => 1;

1;
