# Do NOT edit this file!
# It was generated by IdlC from ExternalSensorManager.idl.

use strict;

package Raritan::RPC::sensors::ExternalSensorManager::Events;

use constant EVT_KEY_SETTINGS_CHANGED => 0;
use constant EVT_KEY_EXTERNALSENSOR_ADDED => 1;
use constant EVT_KEY_EXTERNALSENSOR_REMOVED => 2;

1;
