# Do NOT edit this file!
# It was generated by IdlC from ExternalSensorManager.idl.

use strict;

package Raritan::RPC::sensors::ExternalSensorManager::ZCoordMode;

use constant RACKUNITS => 0;
use constant FREEFORM => 1;

1;
