# Do NOT edit this file!
# It was generated by IdlC from DisplayControl.idl.

use strict;

package Raritan::RPC::display::DisplayControl::DefaultViewItem;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'id'} = "$in->{'id'}";
    $encoded->{'description'} = "$in->{'description'}";
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'id'} = $in->{'id'};
    $decoded->{'description'} = $in->{'description'};
    return $decoded;
}

1;
