# Do NOT edit this file!
# It was generated by IdlC from EventEngine.idl.

use strict;

package Raritan::RPC::event::Engine_1_0_1::Condition::MatchType;

use constant ASSERTED => 0;
use constant DEASSERTED => 1;
use constant BOTH => 2;

1;
