# Do NOT edit this file!
# It was generated by IdlC from TestDisplay.idl.

use strict;

package Raritan::RPC::test::Display::Orientation;

use constant NORMAL => 0;
use constant FLIPPED => 1;
use constant LEFT => 2;
use constant RIGHT => 3;

1;
