# Do NOT edit this file!
# It was generated by IdlC from OverCurrentProtector.idl.

use strict;

package Raritan::RPC::pdumodel::OverCurrentProtector_1_2_2::Type;

use constant BREAKER_1POLE => 0;
use constant BREAKER_2POLE => 1;
use constant BREAKER_3POLE => 2;
use constant FUSE => 3;
use constant FUSE_PAIR => 4;

1;
