# Do NOT edit this file!
# It was generated by IdlC from Modbus.idl.

use strict;

package Raritan::RPC::devsettings::Modbus_2_0_0::Parity;

use constant NONE => 0;
use constant EVEN => 1;
use constant ODD => 2;

1;
