# Do NOT edit this file!
# It was generated by IdlC from UserManager.idl.

use strict;

package Raritan::RPC::usermgmt::AccountEvent;

use constant typeId => "usermgmt.AccountEvent:1.0.0";
use Raritan::RPC::event::UserEvent;

sub encode {
    my ($in) = @_;
    my $encoded = Raritan::RPC::event::UserEvent::encode($in);
    $encoded->{'username'} = "$in->{'username'}";
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = Raritan::RPC::event::UserEvent::decode($agent, $in);
    $decoded->{'username'} = $in->{'username'};
    return $decoded;
}

Raritan::RPC::Registry::registerCodecClass('usermgmt.AccountEvent', 1, 0, 0, 'Raritan::RPC::usermgmt::AccountEvent');
1;
