# Do NOT edit this file!
# It was generated by IdlC from User.idl.

use strict;

package Raritan::RPC::usermgmt::Preferences;


sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'temperatureUnit'} = $in->{'temperatureUnit'};
    $encoded->{'lengthUnit'} = $in->{'lengthUnit'};
    $encoded->{'pressureUnit'} = $in->{'pressureUnit'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'temperatureUnit'} = $in->{'temperatureUnit'};
    $decoded->{'lengthUnit'} = $in->{'lengthUnit'};
    $decoded->{'pressureUnit'} = $in->{'pressureUnit'};
    return $decoded;
}

1;
