# Do NOT edit this file!
# It was generated by IdlC from RoleManager.idl.

use strict;

package Raritan::RPC::usermgmt::RoleEvent;

use constant typeId => "usermgmt.RoleEvent:1.0.0";
use Raritan::RPC::event::UserEvent;

sub encode {
    my ($in) = @_;
    my $encoded = Raritan::RPC::event::UserEvent::encode($in);
    $encoded->{'rolename'} = "$in->{'rolename'}";
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = Raritan::RPC::event::UserEvent::decode($agent, $in);
    $decoded->{'rolename'} = $in->{'rolename'};
    return $decoded;
}

Raritan::RPC::Registry::registerCodecClass('usermgmt.RoleEvent', 1, 0, 0, 'Raritan::RPC::usermgmt::RoleEvent');
1;
