# Do NOT edit this file!
# It was generated by IdlC from AssetStripConfig.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetStripConfig::Events;

use constant EVT_KEY_SETTINGS_CHANGED => 0;

1;
