# Do NOT edit this file!
# It was generated by IdlC from AssetStripConfig.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetStripConfig::LEDOperationMode;

use constant LED_OPERATION_MANUAL => 0;
use constant LED_OPERATION_AUTO => 1;

1;
