# Do NOT edit this file!
# It was generated by IdlC from Firmware.idl.

use strict;

package Raritan::RPC::firmware::UpdateFlags;

use constant CROSS_OEM => 0;
use constant CROSS_HW => 1;
use constant ALLOW_UNTRUSTED => 2;

1;
