# Do NOT edit this file!
# It was generated by IdlC from Firmware.idl.

use strict;

package Raritan::RPC::firmware::UpdateHistoryStatus;

use constant SUCCESSFUL => 0;
use constant FAILED => 1;
use constant INCOMPLETE => 2;

1;
