# Do NOT edit this file!
# It was generated by IdlC from AssetStrip.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetStrip_2_0_3::FirmwareUpdateState;

use constant UPDATE_STARTED => 0;
use constant UPDATE_SUCCESSFUL => 1;
use constant UPDATE_FAILED => 2;

1;
