# Do NOT edit this file!
# It was generated by IdlC from Webcam.idl.

use strict;

package Raritan::RPC::webcam::ImageMetaData;

use Raritan::RPC::webcam::Format_2_0_0;
use Raritan::RPC::webcam::Location;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'format'} = Raritan::RPC::webcam::Format_2_0_0::encode($in->{'format'});
    $encoded->{'timestamp'} = 1 * $in->{'timestamp'};
    $encoded->{'location'} = Raritan::RPC::webcam::Location::encode($in->{'location'});
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'format'} = Raritan::RPC::webcam::Format_2_0_0::decode($agent, $in->{'format'});
    $decoded->{'timestamp'} = $in->{'timestamp'};
    $decoded->{'location'} = Raritan::RPC::webcam::Location::decode($agent, $in->{'location'});
    return $decoded;
}

1;
