# Do NOT edit this file!
# It was generated by IdlC from Webcam.idl.

use strict;

package Raritan::RPC::webcam::PixelFormat;

use constant MJPEG => 0;
use constant JPEG => 1;
use constant RGB => 2;
use constant YUV => 3;

1;
