# Do NOT edit this file!
# It was generated by IdlC from WebcamManager.idl.

use strict;

package Raritan::RPC::webcam::Priority;

use constant VERY_LOW => 0;
use constant LOW => 1;
use constant NORMAL => 2;
use constant HIGH => 3;
use constant VERY_HIGH => 4;

1;
