# Do NOT edit this file!
# It was generated by IdlC from SensorLogger.idl.

use strict;

package Raritan::RPC::sensors::Logger_2_0_1::Events;

use constant EVT_KEY_SETTINGS_CHANGED => 0;
use constant EVT_KEY_LOGGED_SENSORS_CHANGED => 1;

1;
