# Do NOT edit this file!
# It was generated by IdlC from LdapServerSettings.idl.

use strict;

package Raritan::RPC::auth::ldapsrv::SecurityProtocol;

use constant SEC_PROTO_NONE => 0;
use constant SEC_PROTO_SSL => 1;
use constant SEC_PROTO_STARTTLS => 2;

1;
