# Do NOT edit this file!
# It was generated by IdlC from LdapServerSettings.idl.

use strict;

package Raritan::RPC::auth::ldapsrv::ServerType;

use constant ACTIVE_DIRECTORY => 0;
use constant OPEN_LDAP => 1;

1;
