# Do NOT edit this file!
# It was generated by IdlC from Event.idl.

use strict;

package Raritan::RPC::idl::Event;

use constant typeId => "idl.Event:1.0.0";
sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'source'} = Raritan::RPC::ObjectCodec::encode($in->{'source'});
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'source'} = Raritan::RPC::ObjectCodec::decode($agent, $in->{'source'}, 'idl.Object');
    return $decoded;
}

Raritan::RPC::Registry::registerCodecClass('idl.Event', 1, 0, 0, 'Raritan::RPC::idl::Event');
1;
