# Do NOT edit this file!
# It was generated by IdlC from PeripheralDeviceManager.idl.

use strict;

package Raritan::RPC::peripheral::DeviceManager_2_0_1::DeviceFirmwareUpdateState;

use constant UPDATE_STARTED => 0;
use constant UPDATE_SUCCESSFUL => 1;
use constant UPDATE_FAILED => 2;

1;
