# Do NOT edit this file!
# It was generated by IdlC from Circuit.idl.

use strict;

package Raritan::RPC::pdumodel::Circuit::Type;

use constant ONE_PHASE_LN => 0;
use constant ONE_PHASE_LL => 1;
use constant ONE_PHASE_LLN => 2;
use constant THREE_PHASE => 3;

1;
