# Do NOT edit this file!
# It was generated by IdlC from LhxParameter.idl.

use strict;

package Raritan::RPC::lhxmodel::Parameter::Events;

use constant EVT_KEY_VALUE_CHANGED => 0;
use constant EVT_KEY_METADATA_CHANGED => 1;

1;
