# Do NOT edit this file!
# It was generated by IdlC from PeripheralDeviceManager.idl.

use strict;

package Raritan::RPC::peripheral::DeviceManager_1_0_1::Events;

use constant EVT_KEY_SETTINGS_CHANGED => 0;
use constant EVT_KEY_DEVICE_ADDED => 1;
use constant EVT_KEY_DEVICE_REMOVED => 2;

1;
