# Do NOT edit this file!
# It was generated by IdlC from AssetStrip.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetStrip::LEDMode;

use constant LED_MODE_ON => 0;
use constant LED_MODE_OFF => 1;
use constant LED_MODE_BLINK_FAST => 2;
use constant LED_MODE_BLINK_SLOW => 3;

1;
