# Do NOT edit this file!
# It was generated by IdlC from AssetStrip.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetStrip::LEDOperationMode;

use constant LED_OPERATION_MANUAL => 0;
use constant LED_OPERATION_AUTO => 1;

1;
