# Do NOT edit this file!
# It was generated by IdlC from AssetStrip.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetStrip::NumberingMode;

use constant TOP_DOWN => 0;
use constant BOTTOM_UP => 1;

1;
