# Do NOT edit this file!
# It was generated by IdlC from AssetStrip.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetStrip::ScanMode;

use constant SCANMODE_DISABLED => 0;
use constant SCANMODE_BOTH => 1;

1;
