# Do NOT edit this file!
# It was generated by IdlC from AssetStrip.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetStrip::TagInfo;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'channel'} = 1 * $in->{'channel'};
    $encoded->{'familyDesc'} = "$in->{'familyDesc'}";
    $encoded->{'rawId'} = "$in->{'rawId'}";
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'channel'} = $in->{'channel'};
    $decoded->{'familyDesc'} = $in->{'familyDesc'};
    $decoded->{'rawId'} = $in->{'rawId'};
    return $decoded;
}

1;
