# Do NOT edit this file!
# It was generated by IdlC from Net.idl.

use strict;

package Raritan::RPC::net::AuthenticationMode;

use constant AUTH_NONE => 0;
use constant AUTH_PSK => 1;
use constant AUTH_EAP => 2;

1;
