# Do NOT edit this file!
# It was generated by IdlC from Net.idl.

use strict;

package Raritan::RPC::net::CommonInfoChangedEvent;

use constant typeId => "net.CommonInfoChangedEvent:1.0.0";
use Raritan::RPC::idl::Event;
use Raritan::RPC::net::CommonInfo;

sub encode {
    my ($in) = @_;
    my $encoded = Raritan::RPC::idl::Event::encode($in);
    $encoded->{'commonInfo'} = Raritan::RPC::net::CommonInfo::encode($in->{'commonInfo'});
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = Raritan::RPC::idl::Event::decode($agent, $in);
    $decoded->{'commonInfo'} = Raritan::RPC::net::CommonInfo::decode($agent, $in->{'commonInfo'});
    return $decoded;
}

Raritan::RPC::Registry::registerCodecClass('net.CommonInfoChangedEvent', 1, 0, 0, 'Raritan::RPC::net::CommonInfoChangedEvent');
1;
