# Do NOT edit this file!
# It was generated by IdlC from Net.idl.

use strict;

package Raritan::RPC::net::EapSettings;


sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'identity'} = "$in->{'identity'}";
    $encoded->{'password'} = "$in->{'password'}";
    $encoded->{'outerMethod'} = $in->{'outerMethod'};
    $encoded->{'innerMethod'} = $in->{'innerMethod'};
    $encoded->{'caCertificate'} = "$in->{'caCertificate'}";
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'identity'} = $in->{'identity'};
    $decoded->{'password'} = $in->{'password'};
    $decoded->{'outerMethod'} = $in->{'outerMethod'};
    $decoded->{'innerMethod'} = $in->{'innerMethod'};
    $decoded->{'caCertificate'} = $in->{'caCertificate'};
    return $decoded;
}

1;
