# Do NOT edit this file!
# It was generated by IdlC from Net.idl.

use strict;

package Raritan::RPC::net::EthDuplexMode;

use constant DUPLEX_MODE_AUTO => 0;
use constant DUPLEX_MODE_HALF => 1;
use constant DUPLEX_MODE_FULL => 2;

1;
