# Do NOT edit this file!
# It was generated by IdlC from Net.idl.

use strict;

package Raritan::RPC::net::EthSpeed;

use constant SPEED_AUTO => 0;
use constant SPEED_MBIT_10 => 1;
use constant SPEED_MBIT_100 => 2;
use constant SPEED_MBIT_1000 => 3;

1;
