# Do NOT edit this file!
# It was generated by IdlC from Net.idl.

use strict;

package Raritan::RPC::net::InterfaceType;

use constant ETHERNET => 0;
use constant WLAN => 1;
use constant BRIDGE => 2;

1;
