# Do NOT edit this file!
# It was generated by IdlC from Net.idl.

use strict;

package Raritan::RPC::net::InterfaceMode_2_0_0;

use constant IF_MODE_WIRED => 0;
use constant IF_MODE_WIRELESS => 1;
use constant IF_MODE_USB_DEVICE => 2;

1;
