# Do NOT edit this file!
# It was generated by IdlC from Net.idl.

use strict;

package Raritan::RPC::net::IpAddrCidr;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'addr'} = "$in->{'addr'}";
    $encoded->{'prefixLen'} = 1 * $in->{'prefixLen'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'addr'} = $in->{'addr'};
    $decoded->{'prefixLen'} = $in->{'prefixLen'};
    return $decoded;
}

1;
