# Do NOT edit this file!
# It was generated by IdlC from Net.idl.

use strict;

package Raritan::RPC::net::IpConfigMethod;

use constant STATIC => 0;
use constant DHCP => 1;
use constant AUTO => 2;

1;
