# Do NOT edit this file!
# It was generated by IdlC from Net.idl.

use strict;

package Raritan::RPC::net::LanDuplex;

use constant LAN_DUPLEX_AUTO => 0;
use constant LAN_DUPLEX_HALF => 1;
use constant LAN_DUPLEX_FULL => 2;
use constant LAN_DUPLEX_UNKNOWN => 3;

1;
