# Do NOT edit this file!
# It was generated by IdlC from Net.idl.

use strict;

package Raritan::RPC::net::LanLinkMode;


sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'speed'} = $in->{'speed'};
    $encoded->{'duplex'} = $in->{'duplex'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'speed'} = $in->{'speed'};
    $decoded->{'duplex'} = $in->{'duplex'};
    return $decoded;
}

1;
