# Do NOT edit this file!
# It was generated by IdlC from Net.idl.

use strict;

package Raritan::RPC::net::LanSpeed;

use constant LAN_SPEED_AUTO => 0;
use constant LAN_SPEED_10MBIT => 1;
use constant LAN_SPEED_100MBIT => 2;
use constant LAN_SPEED_1000MBIT => 3;
use constant LAN_SPEED_UNKNOWN => 4;

1;
