# Do NOT edit this file!
# It was generated by IdlC from Net.idl.

use strict;

package Raritan::RPC::net::PortForwardingMasterAddrInfo;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'ifName'} = "$in->{'ifName'}";
    $encoded->{'addr'} = "$in->{'addr'}";
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'ifName'} = $in->{'ifName'};
    $decoded->{'addr'} = $in->{'addr'};
    return $decoded;
}

1;
