# Do NOT edit this file!
# It was generated by IdlC from AssetStrip.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetStrip_2_0_0::Events;

use constant EVT_KEY_STATE_CHANGED => 0;
use constant EVT_KEY_SETTINGS_CHANGED => 1;
use constant EVT_KEY_TAGS_CHANGED => 2;

1;
