# Do NOT edit this file!
# It was generated by IdlC from LhxConfig.idl.

use strict;

package Raritan::RPC::lhxmodel::Config::ComSettings;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'devAddr'} = 1 * $in->{'devAddr'};
    $encoded->{'lhxAddr'} = 1 * $in->{'lhxAddr'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'devAddr'} = $in->{'devAddr'};
    $decoded->{'lhxAddr'} = $in->{'lhxAddr'};
    return $decoded;
}

1;
