# Do NOT edit this file!
# It was generated by IdlC from LhxConfig.idl.

use strict;

package Raritan::RPC::lhxmodel::Config::Events;

use constant EVT_KEY_COMSETTINGS_CHANGED => 0;
use constant EVT_KEY_PORTNAME_CHANGED => 1;

1;
