# Do NOT edit this file!
# It was generated by IdlC from PowerLogicPowerMeter.idl.

use strict;

package Raritan::RPC::powerlogic::PowerMeter_1_1_1::Events;

use constant EVT_KEY_SETUP_CHANGED => 0;
use constant EVT_KEY_ERROR_STATUS_CHANGED => 1;

1;
