# Do NOT edit this file!
# It was generated by IdlC from SerialPort.idl.

use strict;

package Raritan::RPC::serial::SerialPort::PortState;

use constant CONSOLE => 0;
use constant ANALOGMODEM => 1;
use constant GSMMODEM => 2;

1;
