# Do NOT edit this file!
# It was generated by IdlC from Log.idl.

use strict;

package Raritan::RPC::logging::LogInfo;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'creationTime'} = 1 * $in->{'creationTime'};
    $encoded->{'idFirst'} = 1 * $in->{'idFirst'};
    $encoded->{'idNext'} = 1 * $in->{'idNext'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'creationTime'} = $in->{'creationTime'};
    $decoded->{'idFirst'} = $in->{'idFirst'};
    $decoded->{'idNext'} = $in->{'idNext'};
    return $decoded;
}

1;
