# Do NOT edit this file!
# It was generated by IdlC from ServerSSLCert.idl.

use strict;

package Raritan::RPC::cert::ServerSSLCert::CommonAttributes;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'country'} = "$in->{'country'}";
    $encoded->{'stateOrProvince'} = "$in->{'stateOrProvince'}";
    $encoded->{'locality'} = "$in->{'locality'}";
    $encoded->{'organization'} = "$in->{'organization'}";
    $encoded->{'organizationalUnit'} = "$in->{'organizationalUnit'}";
    $encoded->{'commonName'} = "$in->{'commonName'}";
    $encoded->{'emailAddress'} = "$in->{'emailAddress'}";
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'country'} = $in->{'country'};
    $decoded->{'stateOrProvince'} = $in->{'stateOrProvince'};
    $decoded->{'locality'} = $in->{'locality'};
    $decoded->{'organization'} = $in->{'organization'};
    $decoded->{'organizationalUnit'} = $in->{'organizationalUnit'};
    $decoded->{'commonName'} = $in->{'commonName'};
    $decoded->{'emailAddress'} = $in->{'emailAddress'};
    return $decoded;
}

1;
