# Do NOT edit this file!
# It was generated by IdlC from OverCurrentProtector.idl.

use strict;

package Raritan::RPC::pdumodel::CircuitBreakerStatistic;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'tripCnt'} = 1 * $in->{'tripCnt'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'tripCnt'} = $in->{'tripCnt'};
    return $decoded;
}

1;
