# Do NOT edit this file!
# It was generated by IdlC from Outlet.idl.

use strict;

package Raritan::RPC::pdumodel::OutletStatistic;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'relayCycleCnt'} = 1 * $in->{'relayCycleCnt'};
    $encoded->{'relayFailCnt'} = 1 * $in->{'relayFailCnt'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'relayCycleCnt'} = $in->{'relayCycleCnt'};
    $decoded->{'relayFailCnt'} = $in->{'relayFailCnt'};
    return $decoded;
}

1;
