# Do NOT edit this file!
# It was generated by IdlC from Pole.idl.

use strict;

package Raritan::RPC::pdumodel::PowerLine_2_0_0;

use constant L1 => 0;
use constant L2 => 1;
use constant L3 => 2;
use constant NEUTRAL => 3;
use constant EARTH => 4;

1;
