# Do NOT edit this file!
# It was generated by IdlC from Nameplate.idl.

use strict;

package Raritan::RPC::pdumodel::Rating;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'current'} = 1 * $in->{'current'};
    $encoded->{'minVoltage'} = 1 * $in->{'minVoltage'};
    $encoded->{'maxVoltage'} = 1 * $in->{'maxVoltage'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'current'} = $in->{'current'};
    $decoded->{'minVoltage'} = $in->{'minVoltage'};
    $decoded->{'maxVoltage'} = $in->{'maxVoltage'};
    return $decoded;
}

1;
