# Do NOT edit this file!
# It was generated by IdlC from PeripheralG2Production.idl.

use strict;

package Raritan::RPC::peripheral::G2Production_3_0_0::ResetMethod;

use constant BROWNOUT => 0;
use constant WATCHDOG => 1;

1;
