# Do NOT edit this file!
# It was generated by IdlC from ResidualCurrentStateSensor.idl.

use strict;

package Raritan::RPC::pdumodel::ResidualCurrentStateSensor::Events;

use constant EVT_KEY_SETTINGS_CHANGED => 0;

1;
