# Do NOT edit this file!
# It was generated by IdlC from Controller.idl.

use strict;

package Raritan::RPC::pdumodel::Controller_2_0_1::Type;

use constant OUTLET_CTRL => 0;
use constant INLET_CTRL => 1;
use constant METER_CTRL => 2;

1;
