# Do NOT edit this file!
# It was generated by IdlC from AssetManager.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetManager::Settings;

use Raritan::RPC::assetmgrmodel::AssetStrip::LEDColor;
use Raritan::RPC::assetmgrmodel::AssetStrip::LEDColor;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'defaultColorConnected'} = Raritan::RPC::assetmgrmodel::AssetStrip::LEDColor::encode($in->{'defaultColorConnected'});
    $encoded->{'defaultColorDisconnected'} = Raritan::RPC::assetmgrmodel::AssetStrip::LEDColor::encode($in->{'defaultColorDisconnected'});
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'defaultColorConnected'} = Raritan::RPC::assetmgrmodel::AssetStrip::LEDColor::decode($agent, $in->{'defaultColorConnected'});
    $decoded->{'defaultColorDisconnected'} = Raritan::RPC::assetmgrmodel::AssetStrip::LEDColor::decode($agent, $in->{'defaultColorDisconnected'});
    return $decoded;
}

1;
