# Do NOT edit this file!
# It was generated by IdlC from TransferSwitch.idl.

use strict;

package Raritan::RPC::pdumodel::TransferSwitch_2_0_0::Type;

use constant STS => 0;
use constant ATS => 1;
use constant HTS => 2;

1;
