# Do NOT edit this file!
# It was generated by IdlC from Zeroconf.idl.

use strict;

package Raritan::RPC::devsettings::Zeroconf::Settings;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'mdnsEnabled'} = ($in->{'mdnsEnabled'}) ? JSON::true : JSON::false;
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'mdnsEnabled'} = ($in->{'mdnsEnabled'}) ? 1 : 0;
    return $decoded;
}

1;
