# Do NOT edit this file!
# It was generated by IdlC from CardReaderManager.idl.

use strict;

package Raritan::RPC::smartcard::CardReaderManager::CardReaderDetachedEvent;

use constant typeId => "smartcard.CardReaderManager.CardReaderDetachedEvent:1.0.0";
use Raritan::RPC::smartcard::CardReaderManager::CardReaderEvent;

sub encode {
    my ($in) = @_;
    my $encoded = Raritan::RPC::smartcard::CardReaderManager::CardReaderEvent::encode($in);
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = Raritan::RPC::smartcard::CardReaderManager::CardReaderEvent::decode($agent, $in);
    return $decoded;
}

Raritan::RPC::Registry::registerCodecClass('smartcard.CardReaderManager.CardReaderDetachedEvent', 1, 0, 0, 'Raritan::RPC::smartcard::CardReaderManager::CardReaderDetachedEvent');
1;
