# Do NOT edit this file!
# It was generated by IdlC from PeripheralDevicePackage.idl.

use strict;

package Raritan::RPC::peripheral::PackageInfo_2_0_0::State;

use constant NORMAL => 0;
use constant FW_UPDATE => 1;
use constant INTERNAL_ERROR => 2;
use constant CONFIG_ERROR => 3;

1;
