# Do NOT edit this file!
# It was generated by IdlC from AssetStrip.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetStrip_2_0_2::CascadeState;

use constant CASCADE_ACTIVE => 0;
use constant CASCADE_FIRMWARE_UPDATE => 1;

1;
