# Do NOT edit this file!
# It was generated by IdlC from AssetStripConfig.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetStripConfig_1_0_1::Orientation;

use constant TOP_CONNECTOR => 0;
use constant BOTTOM_CONNECTOR => 1;

1;
