# Do NOT edit this file!
# It was generated by IdlC from AssetStripConfig.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetStripConfig_1_0_1::ScanMode;

use constant SCANMODE_DISABLED => 0;
use constant SCANMODE_BOTH => 1;

1;
