# Do NOT edit this file!
# It was generated by IdlC from Modbus.idl.

use strict;

package Raritan::RPC::devsettings::Modbus::Settings;

use Raritan::RPC::devsettings::Modbus::TcpSettings;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'tcp'} = Raritan::RPC::devsettings::Modbus::TcpSettings::encode($in->{'tcp'});
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'tcp'} = Raritan::RPC::devsettings::Modbus::TcpSettings::decode($agent, $in->{'tcp'});
    return $decoded;
}

1;
