# Do NOT edit this file!
# It was generated by IdlC from SerialPort.idl.

use strict;

package Raritan::RPC::serial::SerialPort_1_0_1::BaudRate;

use constant BR1200 => 0;
use constant BR2400 => 1;
use constant BR4800 => 2;
use constant BR9600 => 3;
use constant BR19200 => 4;
use constant BR38400 => 5;
use constant BR57600 => 6;
use constant BR115200 => 7;

1;
