# Do NOT edit this file!
# It was generated by IdlC from SerialPort.idl.

use strict;

package Raritan::RPC::serial::SerialPort_1_0_1::ConsoleSettings;


sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'baudRate'} = $in->{'baudRate'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'baudRate'} = $in->{'baudRate'};
    return $decoded;
}

1;
