# Do NOT edit this file!
# It was generated by IdlC from Security.idl.

use strict;

package Raritan::RPC::security::IpfwRuleset;


sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'ipMask'} = "$in->{'ipMask'}";
    $encoded->{'policy'} = $in->{'policy'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'ipMask'} = $in->{'ipMask'};
    $decoded->{'policy'} = $in->{'policy'};
    return $decoded;
}

1;
