# Do NOT edit this file!
# It was generated by IdlC from Security.idl.

use strict;

package Raritan::RPC::security::IpfwPolicy;

use constant ACCEPT => 0;
use constant DROP => 1;
use constant REJECT => 2;

1;
