# Do NOT edit this file!
# It was generated by IdlC from Security.idl.

use strict;

package Raritan::RPC::security::PasswordSettingsChanged;

use constant typeId => "security.PasswordSettingsChanged:1.0.0";
use Raritan::RPC::security::PasswordSettings;
use Raritan::RPC::security::PasswordSettings;
use Raritan::RPC::event::UserEvent;

sub encode {
    my ($in) = @_;
    my $encoded = Raritan::RPC::event::UserEvent::encode($in);
    $encoded->{'oldSettings'} = Raritan::RPC::security::PasswordSettings::encode($in->{'oldSettings'});
    $encoded->{'newSettings'} = Raritan::RPC::security::PasswordSettings::encode($in->{'newSettings'});
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = Raritan::RPC::event::UserEvent::decode($agent, $in);
    $decoded->{'oldSettings'} = Raritan::RPC::security::PasswordSettings::decode($agent, $in->{'oldSettings'});
    $decoded->{'newSettings'} = Raritan::RPC::security::PasswordSettings::decode($agent, $in->{'newSettings'});
    return $decoded;
}

Raritan::RPC::Registry::registerCodecClass('security.PasswordSettingsChanged', 1, 0, 0, 'Raritan::RPC::security::PasswordSettingsChanged');
1;
