# Do NOT edit this file!
# It was generated by IdlC from PeripheralDeviceManager.idl.

use strict;

package Raritan::RPC::peripheral::DeviceManager_2_0_2::FirmwareUpdateState;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'active'} = ($in->{'active'}) ? JSON::true : JSON::false;
    $encoded->{'remaining'} = 1 * $in->{'remaining'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'active'} = ($in->{'active'}) ? 1 : 0;
    $decoded->{'remaining'} = $in->{'remaining'};
    return $decoded;
}

1;
