# Do NOT edit this file!
# It was generated by IdlC from PeripheralDeviceManager.idl.

use strict;

package Raritan::RPC::peripheral::DeviceManager_2_0_2::PackageAddedEvent_2_0_0;

use constant typeId => "peripheral.DeviceManager_2_0_2.PackageAddedEvent:2.0.0";
use Raritan::RPC::peripheral::DeviceManager_2_0_2::PackageEvent_2_0_0;

sub encode {
    my ($in) = @_;
    my $encoded = Raritan::RPC::peripheral::DeviceManager_2_0_2::PackageEvent_2_0_0::encode($in);
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = Raritan::RPC::peripheral::DeviceManager_2_0_2::PackageEvent_2_0_0::decode($agent, $in);
    return $decoded;
}

Raritan::RPC::Registry::registerCodecClass('peripheral.DeviceManager_2_0_2.PackageAddedEvent', 2, 0, 0, 'Raritan::RPC::peripheral::DeviceManager_2_0_2::PackageAddedEvent_2_0_0');
1;
