# Do NOT edit this file!
# It was generated by IdlC from AuthManager.idl.

use strict;

package Raritan::RPC::auth::Policy;


sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'type'} = $in->{'type'};
    $encoded->{'useLocalIfRemoteFailed'} = ($in->{'useLocalIfRemoteFailed'}) ? JSON::true : JSON::false;
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'type'} = $in->{'type'};
    $decoded->{'useLocalIfRemoteFailed'} = ($in->{'useLocalIfRemoteFailed'}) ? 1 : 0;
    return $decoded;
}

1;
