# Do NOT edit this file!
# It was generated by IdlC from AuthManager.idl.

use strict;

package Raritan::RPC::auth::Type;

use constant LOCAL => 0;
use constant RADIUS => 1;
use constant KERBEROS => 2;
use constant TACACS_PLUS => 3;
use constant LDAP => 4;

1;
