# Do NOT edit this file!
# It was generated by IdlC from LhxDevel.idl.

use strict;

package Raritan::RPC::lhxmodel::LhxDevel_1_1_1::ParameterData;

use Raritan::RPC::lhxmodel::Parameter_2_0_1::MetaData;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'value'} = 1 * $in->{'value'};
    $encoded->{'rawValue'} = 1 * $in->{'rawValue'};
    $encoded->{'metadata'} = Raritan::RPC::lhxmodel::Parameter_2_0_1::MetaData::encode($in->{'metadata'});
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'value'} = $in->{'value'};
    $decoded->{'rawValue'} = $in->{'rawValue'};
    $decoded->{'metadata'} = Raritan::RPC::lhxmodel::Parameter_2_0_1::MetaData::decode($agent, $in->{'metadata'});
    return $decoded;
}

1;
