# Do NOT edit this file!
# It was generated by IdlC from Outlets.idl.

use strict;

package Raritan::RPC::pdumodel::Outlets::Info;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'numberOfOutlets'} = 1 * $in->{'numberOfOutlets'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'numberOfOutlets'} = $in->{'numberOfOutlets'};
    return $decoded;
}

1;
