# Do NOT edit this file!
# It was generated by IdlC from Unit.idl.

use strict;

package Raritan::RPC::pdumodel::Unit_1_0_1::Settings;


sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'buzzerMuted'} = ($in->{'buzzerMuted'}) ? JSON::true : JSON::false;
    $encoded->{'autoDisplayOrientation'} = ($in->{'autoDisplayOrientation'}) ? JSON::true : JSON::false;
    $encoded->{'displayOrientation'} = $in->{'displayOrientation'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'buzzerMuted'} = ($in->{'buzzerMuted'}) ? 1 : 0;
    $decoded->{'autoDisplayOrientation'} = ($in->{'autoDisplayOrientation'}) ? 1 : 0;
    $decoded->{'displayOrientation'} = $in->{'displayOrientation'};
    return $decoded;
}

1;
