# Do NOT edit this file!
# It was generated by IdlC from Cascading.idl.

use strict;

package Raritan::RPC::cascading::Cascading::Type;

use constant USB_MULTI_IP => 0;
use constant USB_SINGLE_IP_NAT => 1;

1;
