# Do NOT edit this file!
# It was generated by IdlC from DataPushService.idl.

use strict;

package Raritan::RPC::event::DataPushService::EntryType;

use constant SENSORLIST => 0;
use constant SENSORLOG => 1;
use constant AMSLIST => 2;
use constant AMSLOG => 3;
use constant AUDITLOG => 4;

1;
