# Do NOT edit this file!
# It was generated by IdlC from OverCurrentProtectors.idl.

use strict;

package Raritan::RPC::pdumodel::OverCurrentProtectors::Info;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'numberOfOCPs'} = 1 * $in->{'numberOfOCPs'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'numberOfOCPs'} = $in->{'numberOfOCPs'};
    return $decoded;
}

1;
