# Do NOT edit this file!
# It was generated by IdlC from Smtp.idl.

use strict;

package Raritan::RPC::devsettings::Smtp_2_0_0::TestResult;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'status'} = 1 * $in->{'status'};
    $encoded->{'message'} = "$in->{'message'}";
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'status'} = $in->{'status'};
    $decoded->{'message'} = $in->{'message'};
    return $decoded;
}

1;
