# Do NOT edit this file!
# It was generated by IdlC from Pdu.idl.

use strict;

package Raritan::RPC::pdumodel::Pdu_1_4_2::Events;

use constant EVT_KEY_SETTINGS_CHANGED => 0;
use constant EVT_KEY_LOADSHEDDING_MODE_CHANGED => 1;
use constant EVT_KEY_OUTLETSEQUENCE_STATE_CHANGED => 2;

1;
